config/routes.rb
Rails.application.routes.draw do
  
  
  root "flights#index"
  get "/flights", to: "flights#index"
  resources :passengers
  resources :bookings
  
  

  
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departures, foreign_key: "depart_airport_id", class_name: "Flight"
    has_many :arrivals, foreign_key: "arrive_airport_id", class_name: "Flight"

    def code_and_location
        self.code + " " + self.city + ", " + self.state
    end

    def location
        self.city + ", " + self.state
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    has_many :passengers_bookings
    has_many :passengers, through: :passengers_bookings
    belongs_to :flight
    accepts_nested_attributes_for :passengers

    def create_booking_confirmation
        alphabet = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
        alphabet[rand(0..25)].upcase + alphabet[rand(0..25)].upcase + rand(10..99).to_s + alphabet[rand(0..25)].upcase + alphabet[rand(0..25)].upcase + rand(10..99).to_s
    end
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :depart_airport, class_name: "Airport"
    belongs_to :arrive_airport, class_name: "Airport"
    has_many :bookings
    has_many :passengers, through: :bookings

    def display_text
        self.time.to_time.strftime("%I:%M %p") + " departure from " + self.depart_airport.code_and_location + " arrives at " + self.arrive_airport.code_and_location
    end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    has_many :passengers_bookings
    has_many :bookings, through: :passengers_bookings
    has_many :flights, through: :bookings
end

app/models/passengers_booking.rb
class PassengersBooking < ApplicationRecord
    belongs_to :booking
    belongs_to :passenger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
    @passengers = @booking.passengers
  end

  def new
    @booking = Booking.new(flight_id: params[:flight_id])
    @passenger_count = params[:num_passengers].to_i
    @passenger_count.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      @booking.passengers.each { |passenger| PassengerMailer.booking_confirmation_email(@booking, passenger).deliver_now }
      
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def booking_params
    params.require(:booking).permit(:id, :confirmation, :flight_id, 
      passengers_attributes: [:id, :name, :email]
    ) 
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    
    def index
        @arrive_airports = Airport.all.select { |ap| ap.departures.present? }
        @depart_airports = Airport.all.select { |ap| ap.arrivals.present? }
        @num_passengers = [1, 2, 3, 4]
        @flights = Flight.where(depart_airport_id: request.parameters[:depart_airport_id]).where(arrive_airport_id: request.parameters[:arrive_airport_id]).where(date: request.parameters[:date])
        @passenger_count = request.parameters[:num_passengers]
    end
    
    

end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  def index
  end

  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flight_helper.rb
module FlightHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>

<%= form_with model: @booking do |f| %>
    <%= f.hidden_field :confirmation, value: @booking.create_booking_confirmation %>
    <%= f.hidden_field :flight_id, value: @booking.flight_id %>
        <%= f.fields_for :passengers do |f_pass| %>
            <%= f_pass.text_field  :name, placeholder: "Enter passenger name" %>
            <%= f_pass.text_field  :email, placeholder: "Enter passenger email" %>
        <% end %>
    <%= f.submit "Book Flight" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Bookings#index</h1>
<h2><%= @booking.confirmation %></h2>
<p><%= @flight.display_text %></p>
<ul> Passengers: 
    <% @passengers.each do |pass| %>
        <li><%= pass.name %></li>
    <% end %>
</ul>

app/views/flights/_flight_search_form.html.erb
<h2>Flights#search</h2>

<%= form_with url: flights_path, method: :get do |f| %>
    <%= f.label :depart_airport_id, "Origin:" %>
    <%= f.collection_select :depart_airport_id, @depart_airports, :id, :code_and_location %>
        
    <%= f.label :arrive_airport_id, "Destination:" %>
    <%= f.collection_select :arrive_airport_id, @arrive_airports, :id, :code_and_location %>

    <%= f.label :flights, "Passengers:" %>
    <%= f.select :num_passengers, @num_passengers %>
    
    <%= f.label :date, "Travel Date:" %>
    <%= f.date_field  :date %>

    <%= f.submit "Find Flights" %>
<% end %>

app/views/flights/_flight_select_form.html.erb
<h2>Flights#select</h2>

<%= form_with(model: @flight, url: new_booking_path, method: "get") do |f| %>
    <%= f.hidden_field :num_passengers, value: @passenger_count %>
    <%= f.collection_radio_buttons :flight_id, @flights, :id, :display_text %>
    <%= f.submit "Select Flight" %>
<% end %>

app/views/flights/index.html.erb
<h1>Flights#Index</h1>

<%= render "flight_search_form" %>

<% if @flights.present? %>
    <%= render "flight_select_form" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/passengers/index.html.erb
<h1>Passengers#index</h1>
<p>Find me in app/views/passengers/index.html.erb</p>

app/views/passengers/new.html.erb
<h1>Passengers#new</h1>
<p>Find me in app/views/passengers/new.html.erb</p>